# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'DYZB' do

pod 'Alamofire', '~>4.2.0'
pod 'Kingfisher', '~>3.2.1'
pod 'SnapKit'

end
